version: '3.6'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: maze
      POSTGRES_PASSWORD: maze123
    ports:
      - "6432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data